### ISSUE TITLE
[Feature] Option to set private server endpoint on the verification code page in setup wizard 

### ISSUE THREAD

**Issue by kennethjiang** [TheSpaghettiDetective/OctoPrint-TheSpaghettiDetective#104]
**Is your feature request related to a problem? Please describe.**
The setup wizard, which initially launched, doesn't provide an option to set the endpoint to a private TSD server. And hence it can't be linked to a private server.

**Describe the solution you'd like**
Have an option to set the endpoint to a private TSD server in setup wizard.

**Describe alternatives you've considered**
The current workaround is to click "Finish" to dismiss the wizard. Set the endpoint in the settings, then "Re-run wizard" to finish the linking pro ess.

**Comment by trowj** [comment]
Perhaps I'm misunderstanding the notes here, but I couldn't even set a custom URL by dismissing the wizard initially - the plugin section in settings didn't have anything except a logo. I had to connect my OctoPrint to a real TSD account/printer, then I could go into settings and change the URL and re-run the wizard.

**Comment by kennethjiang** [comment]
@trowj This sounds like another bug. Are you able to reproduce the problem? If so, please provide the steps. Thank you so much!

**Comment by kennethjiang** [comment]
Actually we found the bug and included the fix in 1.5.1 that we just released

**Comment by kennethjiang** [comment]
Fixed in version 1.5.1
