### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by darigovresearch** [TheSpaghettiDetective/OctoPrint-TheSpaghettiDetective#109]
Noticed that the repository doesn't have a license attached to it. You may get more pull requests if an open source friendly license is selected.

Am assuming it would be AGPL-3.0 License like the Spaghetti Detective server - https://github.com/TheSpaghettiDetective/TheSpaghettiDetective

Was there a discussion that we missed as to why there isn't a license for this repository?

Happy to make a pull request if that helps

**Comment by darigovresearch** [comment]
Merging pull request https://github.com/TheSpaghettiDetective/OctoPrint-TheSpaghettiDetective/pull/110 would resolve this issue

**Comment by kennethjiang** [comment]
Solved in #110
