### ISSUE TITLE
[Feature] Add option to match the way that themify and other similar Octoprint plugins change the color scheme of Octoprint.

### ISSUE THREAD

**Issue by ryryog25** [TheSpaghettiDetective/OctoPrint-TheSpaghettiDetective#111]
One thing that has really been bugging me is that "themify" which I always run and makes Octoprint super cool looking (IMO) does not play nicely with TSD. 

For example, (and I have linked screenshots of all these below) the TSD plugin menu tabs just don't look good, they are white as that is the normal background of Octoprint, but with my setup (which is more of a gray background) it doesn't look anywhere near as sleek.

The Setup Wizard interestingly doesn't actually get switched from black to white text so it pops correctly (The plugin normally changes text so that it does in fact pop, and there are multiple different combinations of color schemes...) leaving the setup wizard basically impossible to read without straining your eyes.

After this the only thing that is truly broken in the Octoprint TSD plugin is the part where you enter in the 6-digit verification code and the background appears to be changed by the plugin, but the rest of the field, which I assume is not actually a part of the text field but rather a UI element, is white.

The white buttons are fine, I actually think they pop really well with the dark background, so I would almost say I don't want those removed, same for the white logos.

Everything else the plugin does a really good job of converting, so that would be it, unless I missed something.

It would be great if the TSD plugin could somehow adapt to these to make the UI flow as it does with vanilla Octoprint.

I don't really know how this would work, since I have a feeling those UI elements are just SVGs or something, so you would almost need to specifically create more SVGs that looked the same as themify's current settings and then be able to pull what it was set to.

SCREENSHOTS:
<img width="1362" alt="Screen Shot 2021-03-03 at 2 50 59 PM" src="https://user-images.githubusercontent.com/60193408/109870659-00e1bb00-7c30-11eb-97ad-776845f71579.png">
<img width="1362" alt="Screen Shot 2021-03-03 at 2 51 24 PM" src="https://user-images.githubusercontent.com/60193408/109870666-03441500-7c30-11eb-993a-49a43475e7be.png">
<img width="1362" alt="Screen Shot 2021-03-03 at 2 51 37 PM" src="https://user-images.githubusercontent.com/60193408/109870672-03dcab80-7c30-11eb-9220-5888dfb75b84.png">

**Comment by kennethjiang** [comment]
Thank you so much @ryryog25 for such a good bug report!

**Comment by kennethjiang** [comment]
We fixed other issues except the tabs in the settings. We feel the default tabs don't really flow well with the rest of our settings page. So our designer added while border at the bottom to make it less strange in dark theme.

<img width="1266" alt="Screen Shot 2021-03-21 at 8 07 07 AM" src="https://user-images.githubusercontent.com/779786/111909956-85984b80-8a1c-11eb-97e2-23a1264619f9.png">

**Comment by kennethjiang** [comment]
Fixed in 1.6.2

**Comment by ryryog25** [comment]
This looks great! Having that extra bar does go a long way to make it look less strange with themify. I noticed that if I have the window smaller I get a UI that looks like this: 

<img width="931" alt="Screen Shot 2021-03-21 at 10 26 41 AM" src="https://user-images.githubusercontent.com/60193408/111910573-eed58a00-8a2f-11eb-8654-3e1a04b6078c.png">

I know this would affect the entire plugin UI and it is a rather selfish at this point, but just as an idea I wonder how it would look it this kind of style was kept all the time? I appreciate the work you have already done to fix this, just wanted to throw this in the air so at the very least it is out there, whether it is used or not.

Again, thank you for taking a look at this!

**Comment by kennethjiang** [comment]
Bringing issues about product is never a selfish thing, as there are always other users who have the same problem.

Yes we made a decision decision to go simple when the screen is narrower, assuming most users use OctoPrint on the computer (or use Touch UI on the phone). Did you open this on an iPad?

**Comment by ryryog25** [comment]
I use octoprint on my iPad a lot, but that particular screenshot was just a small browser window. I noticed that the TSD design did that when in a smaller form factor and was kind of wondering if there was a way to tell if themify was being used and use that design all the time? Idk, just a thought.
