### ISSUE TITLE
[BUG] (More like improvement) Please use unique IDs for tabs in settings

### ISSUE THREAD

**Issue by cp2004** [TheSpaghettiDetective/OctoPrint-TheSpaghettiDetective#114]
In the settings, a tab with the ID `#advanced` is common, and so it sometimes causes conflicts with other plugins. Maybe use it prefixed, such as `#TSD-advanced` so that it doesn't overwrite other tabs from other plugins?

Initially found here: https://github.com/OctoPrint/OctoPrint-FirmwareUpdater/issues/232 - but I think it is worth it that both plugins use less common IDs to avoid future conflicts with more plugins down the road.

**Comment by kennethjiang** [comment]
Fixed in https://github.com/TheSpaghettiDetective/OctoPrint-TheSpaghettiDetective/commit/efc044989fb81660f834c51a7494db862cb02de2

**Comment by cp2004** [comment]
Awesome, thank you 🙂
