### ISSUE TITLE
Temporarily disabling

### ISSUE THREAD

**Issue by pquodling** [TheSpaghettiDetective/OctoPrint-TheSpaghettiDetective#16]
Is there a simple way to disable TSD for a print (short of uninstalling) - I am getting some stringing, need to print something, and am happy to mod the print with a heat gun/knife afterwards, but need it to print. Is there an easy "off" button to allow a print to happen "warts and all".

**Comment by kennethjiang** [comment]
Other users made similar request which I captured at: https://github.com/TheSpaghettiDetective/TheSpaghettiDetective/issues/47

Do you think adding a toggle to "My Printer" page would be good enough for your situation too @pquodling ?

**Comment by pquodling** [comment]
Sounds like a good starting point.

**Comment by kennethjiang** [comment]
@pquodling I am closing this issue as we now have a toggle to temporarily disable alert for the entire print. But feel free to re-open it if you don't think that's good enough.
