### ISSUE TITLE
My Free 250h

### ISSUE THREAD

**Issue by TeaRexHD** [TheSpaghettiDetective/OctoPrint-TheSpaghettiDetective#2]
Hello
My 250 hours of AI detection went too quickly. I only have 15 hours of printing time. That's why I would like more detection again. I would like to have my 235 hours again. I can send you a picture below.

Best regards
Paul

![Obico](https://github.com/TheSpaghettiDetective/OctoPrint-TheSpaghettiDetective/assets/105141526/5310b5df-4924-4b76-a8c7-ecfcec0783f1)

**Comment by Zumbapanda5** [comment]
![Uploading IMG_1227.jpeg…]()

**Comment by TeaRexHD** [comment]
![image](https://github.com/TheSpaghettiDetective/OctoPrint-TheSpaghettiDetective/assets/105141526/b2a64853-157c-4d3e-97c3-27e09be390c1)

**Comment by kennethjiang** [comment]
Github issues are reserved only for bugs. Please go to our discord server https://obico.io/discord/ for questions like this.
