### ISSUE TITLE
Why are you loading garbage from youtube, facebook

### ISSUE THREAD

**Issue by projectoblio** [TheSpaghettiDetective/OctoPrint-TheSpaghettiDetective#30]
Please stop loading iframes to youtube and other subdocuments. There is an iframe to youtube and a div tag linked to facebook. The Youtube Iframe especially has a large amount of data and trackers.

They load every time I refresh my OctoPrint interface, causing it to be slow.

There's no reason to have these trackers or embedded videos loaded on every single page refresh.

**Comment by kennethjiang** [comment]
These links are cached (see attached screenshots). If your browser is loading them every time (it shouldn't), please change the browser settings.

And please don't call them garbage. My friends and I spent hours if not days to create those materials to help users understand the plugin and communicate with us and each other.

If you don't want to see these links, this plugin is probably not for you. Please uninstall the plugin and they will be gone.

<img width="1429" alt="Screen Shot 2019-08-29 at 12 49 50 PM" src="https://user-images.githubusercontent.com/779786/63971600-bb9d6580-ca5b-11e9-839e-623ebfd368fe.png">
