### ISSUE TITLE
Small Inversion Issue

### ISSUE THREAD

**Issue by marklair** [TheSpaghettiDetective/OctoPrint-TheSpaghettiDetective#31]
small issue.... when I view the live feed of TSD, the image is right side up (i may have had to invert it in octoprint)..... but when I view all of the time lapses, they are all upside down.... how to fix?

**Comment by m4rcSA** [comment]
I have the camera rotated (Flip webcam horizontally & Flip webcam vertically) in octoprint, so i have the same problem with having the time lapses upside down.
The live feed looks good

**Comment by RaymondHimle** [comment]
@marklair @m4rcSA Is this still an issue?

**Comment by m4rcSA** [comment]
All it's ok except the telegram notification. It's the only left.
It's odd because the mail notification is correctly rotated.

**Comment by kennethjiang** [comment]
Just pushed a release that should fix it for telegram as well. Please verify it and let me know if the fix works for you @m4rcSA . Thanks!

**Comment by RaymondHimle** [comment]
@m4rcSA is this still an issue? @kennethjiang this likely can be closed.

**Comment by marklair** [comment]
No.... This is no longer an issue

**Comment by m4rcSA** [comment]
> Just pushed a release that should fix it for telegram as well. Please verify it and let me know if the fix works for you @m4rcSA . Thanks!

it's fixed! Thanks!

**Comment by kennethjiang** [comment]
Awesome! Thanks folks!
