### ISSUE TITLE
Wrong National phone prefix

### ISSUE THREAD

**Issue by ochm** [TheSpaghettiDetective/OctoPrint-TheSpaghettiDetective#39]
Please, in User preferences, change the national prefix in phone number for the Czech republic.
The +42 is wrong, correct is +420.

Thank you.

**Comment by kennethjiang** [comment]
Thank you for reporting this bug. It's fixed by https://github.com/TheSpaghettiDetective/TheSpaghettiDetective/commit/99610c51dee7f9d6d8b2c1a48f0ca525401ec0c7. Please wait for the next release.
