### ISSUE TITLE
No more Time-lapse

### ISSUE THREAD

**Issue by jmarc67** [TheSpaghettiDetective/OctoPrint-TheSpaghettiDetective#45]
Hello, i have a problem. 
All is working  perfectly except I have nothing here: https://app.thespaghettidetective.com/prints/ no more time-lapse. 
What can i do ? I was working before but now since 1.08 nothing. Empty prints page

If you have any idea.

Thanks

**Comment by RaymondHimle** [comment]
I see this as well on my self hosted server.

**Comment by jmarc67** [comment]
@RaymondHimle: Yes it' very strange. I don't know why this is like that now. All was ok before.

**Comment by kennethjiang** [comment]
@jmarc67 I thought it was something in your plugin set up but it turned out to be a bug our code  introduced Thursday. I'm pushing it to prod right now and will re-generate all the missing time-lapses

**Comment by jmarc67** [comment]
@kennethjiang Thanks, good news.

**Comment by RaymondHimle** [comment]
This issue can be closed. Issue has been fixed in production and private-servers.
