### ISSUE TITLE
C920 seems to only stream 4:3 low quality?

### ISSUE THREAD

**Issue by kic883** [TheSpaghettiDetective/OctoPrint-TheSpaghettiDetective#54]
I have this issue which my video quality under control is very low with wrong aspect ratio. 
for detail please refer to below URL: 
https://community.octoprint.org/t/c920-seems-to-only-stream-4-3-low-quality/14480
I am using Pi4 2GB with Logitech C920, OctoPrint version 1.4.0
/boot/octopi.txt configured correctly, but problem still existed. 

I found it is cause by The Spaghetti Detective plugin.
This problem gone after I check the 'Disable premium webcam streaming' setting inside The Spaghetti Detective plugin 'Advanced Setting tab'.

**Comment by kennethjiang** [comment]
This is a known issue caused by technical difficulties: https://www.thespaghettidetective.com/docs/more-about-webcam-streaming/#i-configured-webcam-aspect-ratio-to-be-16-9-in-octoprint-settings-but-it-has-become-4-3-now-that-i-have-the-premium-webcam-streaming-why
