### ISSUE TITLE
Webcam feed connection picks up new token but not websocket connection

### ISSUE THREAD

**Issue by kennethjiang** [TheSpaghettiDetective/OctoPrint-TheSpaghettiDetective#6]
Steps to reproduce:

1. Set up the plugin with one token.
2. Change it to another token.
3. BUG: webcam feed will start to use the new token to connect to server. But websocket connection is stuck with the old token.

Fix: disconnect and reconnect websocket when a new token is set.

**Comment by psfales** [comment]
I don't know whether it's related or not, but when setting up the second account, it hung with the "spinning dots" in step 4 (waiting for camera connection).   I waited at least 5 minutes with no change, but when I went to the printers page, the printer was there (but without the image metadata that it, presumably, never got in step 4)

**Comment by kennethjiang** [comment]
@psfales Sorry for missing your comments. The problem you described could be related to this issue. Are you still experiencing this problem after (presumably) restarting OctoPrint?

**Comment by psfales** [comment]
@kennethjiang, thanks - my issue was resolving by restarting OctoPrint.   My March 23 comment was just intended to (possibly) help someone else reproduce the problem

**Comment by kennethjiang** [comment]
Good to know! Thanks @psfales !

**Comment by kennethjiang** [comment]
closing it as 1.5.0 is using a new way by removing the use of token.
