### ISSUE TITLE
1.2.2 Breaks video

### ISSUE THREAD

**Issue by purist69** [TheSpaghettiDetective/OctoPrint-TheSpaghettiDetective#62]
Since installing 1.2.2 this morning my dual feed video has stopped working, specifically the USB feed is no longer working and the raspi camera quality is poor, similar to compatibility mode.

I DID try compatability mode this morning for the free 100 hours of free Detective Hours.

After rebooting a number of times I got it working again, but had to completely remove 1.2.2.

**Comment by purist69** [comment]
I've not been able to reinstall it either, so I can't test changes.

**Comment by purist69** [comment]
I was able to get it reinstalled, same issue though.  to recover properly, I need to uninstall, then reboot, then power cycle and then everything re initializes properly.

**Comment by kennethjiang** [comment]
Can you turn on debug logging and send the log file to `k@thespaghettidetective.com`?

1. Turn on debug logging
2. Restart OctoPrint.
3. View TSD page and wait for a couple of minutes.
4. Download "octoprint.log" file and send it to me.

Find the detailed instructions at: https://www.thespaghettidetective.com/docs/turn-on-debug-logging/

**Comment by purist69** [comment]
sorry to say I'm unable to, I've taken the raspi cam out of my configuration and have repurposed it, partially to get this working, but I also needed the cam for another purpose.

**Comment by kennethjiang** [comment]
Most of the bugs in 1.2.2 have been fixed in 1.2.4. I'm closing it for now. Feel free to re-open it if you still experience problems.
