### ISSUE TITLE
Own Server dialog missing on current plugin. 

### ISSUE THREAD

**Issue by richardhughes260** [TheSpaghettiDetective/OctoPrint-TheSpaghettiDetective#64]
Own Server dialog missing on current plugin

The dialog for the checkbox and server address are no longer under the advanced tab.

**Comment by kennethjiang** [comment]
Can you please hard-refresh the OctoPrint page to see if the setting will show up? If not, please look for javascript errors and let me know if you see any: https://documentation.concrete5.org/tutorials/how-open-browser-console-view-errors. 

Also please post a screenshot here. Thanks!

**Comment by RaymondHimle** [comment]
@richardhughes260 any updates on this issue?

**Comment by richardhughes260** [comment]
SRY! Missed the first note. I installed an older plugin, it worked, then I upgraded, that worked.
Maybe I needed a system restart before I began the process. All is working fine now.

**Comment by RaymondHimle** [comment]
Closing resolved issue

**Comment by RaymondHimle** [comment]
@richardhughes260 Do you have the themify plugin install by chance?

**Comment by richardhughes260** [comment]
no idea what that is.
Might remove Slic3r, have not used it.

[image: image.png]
