### ISSUE TITLE
[Private Server] Using Slash in TSD Plugin "Server Address" Field creates invalid URL link for printer setup link.

### ISSUE THREAD

**Issue by RaymondHimle** [TheSpaghettiDetective/OctoPrint-TheSpaghettiDetective#65]
Cross posting for tracking issue

https://github.com/TheSpaghettiDetective/TheSpaghettiDetective/issues/224

**Comment by kennethjiang** [comment]
Sorry for taking so long to get to this issue. This is more of an issue with outdated documentation, when we changed the code so that it doesn't require trailing /. Fixed in https://github.com/TheSpaghettiDetective/TheSpaghettiDetective/commit/5798674fb24702de394fbaa1e39589ad0693f171
