### ISSUE TITLE
Plugin tabs not working

### ISSUE THREAD

**Issue by markuskruse** [TheSpaghettiDetective/OctoPrint-TheSpaghettiDetective#88]
I use firefox on windows, latest version.

When I go into the plugin and click on Advanced settings or Got problems, nothing happens apart from the tab widget changes state. I'm still stuck on the first page with "Setup".

![bild](https://user-images.githubusercontent.com/6737198/98332888-e3913d00-1fff-11eb-9dd8-e889a5f0db40.png)

**Comment by kennethjiang** [comment]
Sorry for the delay.

Similar problems have been reported before and were solved by hard-refreshing the browser. Can you try that?

**Comment by markuskruse** [comment]
Appreciate the quick response. It worked.
