### ISSUE TITLE
Unable to access advanced tab

### ISSUE THREAD

**Issue by jagr200** [TheSpaghettiDetective/OctoPrint-TheSpaghettiDetective#89]
Running TSD on Octoprint 1.4.2 on Pi 4b. Using my own server to watch the cameras. I am unable to access the advanced tab on TSD in this latest update. I used to be able to but I just installed another instance of Octoprint for another printer and I can not setup those settings in advanced.

**Comment by kennethjiang** [comment]
Sorry somehow I missed your issue.

There is a known issue that advanced tab can't be show in wizard. But usually it shows in OctoPrint settings. So in your situation it doesn't even show in the settings?

**Comment by kennethjiang** [comment]
1.5.0 rewrote the settings page. There is no more "advanced" tab".

**Comment by gstevenson** [comment]
@kennethjiang  Where were the fields that were in the advanced tab moved to? I've just done a local install and now looking how to get to field to enter my IP

**Comment by kennethjiang** [comment]
Sorry for the delay. It's moved here.

<img width="910" alt="Screen Shot 2021-01-26 at 5 01 50 AM" src="https://user-images.githubusercontent.com/779786/105848343-b10a3700-5f93-11eb-9d19-aa70781e5272.png">
