### ISSUE TITLE
1.4.6 Video Issues

### ISSUE THREAD

**Issue by chappy1978** [TheSpaghettiDetective/OctoPrint-TheSpaghettiDetective#95]
Ever since the latest update. Ive been getting video slowdowns and lines in the video feed on Octoprint. Im using a Pi3 with a stock Raspberry Pi Camera.

**Comment by kennethjiang** [comment]
We did make some changes on video streaming in 1.4.6. Please send email to [support at thespaghettidetective dot com] as we may need to ask you for the log file or shareable printer feed to further debug this issue.

**Comment by kennethjiang** [comment]
Closing the issue as we are streamlining the bug process to move all support questions to discord server.
